on:
  push:
    branches:
      - master

jobs:
  runs-on: ubuntu-latest
  steps:
    - uses: JamesIves/github-pages-deploy-action@v4.2.2
      with:
        branch: gh-pages
        folder: .
        target-folder: .